services:
  irc-bot:
    build: .
    container_name: relayarr
    restart: unless-stopped
    ports:
      - "9090:9090"
    volumes:
      - ./bot-data:/data
    env_file:
      - .env
    networks:
      - media

networks:
  media:
    external: true
